apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loggregator-rlp
  namespace: oratos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loggregator-rlp
    spec:
      containers:
      - name: loggregator-rlp
        image: loggregator/rlp
        imagePullPolicy: Always
        env:
        - name: RLP_METRIC_SOURCE_ID
          value: oratos/deployment/loggregator-rlp
        - name: ROUTER_ADDRS
          # TODO: this needs all instances of router, not just a service lb
          #value: doppler-doppler-set.scf.svc.cluster.local
          value: 172.30.179.208
        ports:
        - name: api
          containerPort: 8082
        - name: health
          containerPort: 6061
        volumeMounts:
        - name: loggregator-tls-certs
          mountPath: /srv/certs
          readOnly: true
      - name: loggregator-agent
        image: loggregator/agent
        imagePullPolicy: Always
        env:
        - name: AGENT_METRIC_SOURCE_ID
          value: oratos/deployment/loggregator-rlp
        - name: ROUTER_ADDR
          value: 172.30.179.208
        - name: ROUTER_ADDR_WITH_AZ
          value: 172.30.179.208
        - name: AGENT_PPROF_PORT
          value: "6062"
        - name: AGENT_HEALTH_ENDPOINT_PORT
          value: "6063"
        ports:
        - name: health
          containerPort: 6063
        volumeMounts:
        - name: scf-secrets
          mountPath: /srv/certs
          readOnly: true
      volumes:
      - name: loggregator-tls-certs
        secret:
          secretName: loggregator-tls-certs
      - name: scf-secrets
        secret:
          secretName: secrets-2.14.0-1
